package org.mobeho.calendar;

import org.junit.Test;
import org.mobeho.calendar.hilchati.weak.Shabat;

import java.time.LocalDate;

import static junit.framework.Assert.assertNull;
import static junit.framework.TestCase.assertEquals;

public class HebrewDateTest
{
    @Test
    public void of()
    {
        assertNull(HebrewDate.of("תשרי התשפב"));
        assertNull(HebrewDate.of("א התשפב"));
        assertNull(HebrewDate.of("התשפב"));
        assertNull(HebrewDate.of("התשפב תשרי"));
        assertNull(HebrewDate.of("התשפב תשרי א"));
        assertNull(HebrewDate.of("התשפב א תשרי"));

        assertEquals(HebrewDate.of(5782, 1, 1),   HebrewDate.of("א תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 1),   HebrewDate.of("א רה\"ש התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 1),   HebrewDate.of(5782, 1));
        assertEquals(HebrewDate.of(5782, 1, 2),   HebrewDate.of("ב תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 2),   HebrewDate.of("ראש השנה ב התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 3),   HebrewDate.of("ג תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 3),   HebrewDate.of("צום גדליה התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 4),   HebrewDate.of("ד תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 5),   HebrewDate.of("וילך התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 5),   HebrewDate.of("ה תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 6),   HebrewDate.of("ו תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 7),   HebrewDate.of("ז תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 8),   HebrewDate.of("ח תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 9),   HebrewDate.of("ט תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 10),  HebrewDate.of("י תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 10),  HebrewDate.of("יום כיפור התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 11),  HebrewDate.of("יא תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 12),  HebrewDate.of("יב תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 12),  HebrewDate.of("האזינו התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 13),  HebrewDate.of("יג תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 14),  HebrewDate.of("יד תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 15),  HebrewDate.of("טו תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 15),  HebrewDate.of("חג סוכות התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 16),  HebrewDate.of("טז תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 16),  HebrewDate.of("ב סוכות התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 17),  HebrewDate.of("יז תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 18),  HebrewDate.of("יח תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 19),  HebrewDate.of("יט תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 19),  HebrewDate.of("שבת חול המועד סוכות התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 20),  HebrewDate.of("כ תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 21),  HebrewDate.of("כא תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 22),  HebrewDate.of("כב תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 22),  HebrewDate.of(5782, "שמחת תורה"));
        assertEquals(HebrewDate.of(5782, 1, 23),  HebrewDate.of("כג תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 24),  HebrewDate.of("כד תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 25),  HebrewDate.of("כה תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 26),  HebrewDate.of("כו תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 26),  HebrewDate.of("בראשית התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 27),  HebrewDate.of("כז תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 28),  HebrewDate.of("כח תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 29),  HebrewDate.of("כט תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 30),  HebrewDate.of("ל תשרי התשפב"));
        assertEquals(HebrewDate.of(5782, 1, 30),   HebrewDate.of(5782, "ל תשרי"));
        assertEquals(HebrewDate.of(5782, 1, 30),   HebrewDate.of(5782, 30));
        assertNull(HebrewDate.of("לא תשרי התשפב"));

        assertEquals(HebrewDate.of(5782, 2, 1),   HebrewDate.of("א חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 2),   HebrewDate.of("ב חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 3),   HebrewDate.of("ג חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 3),   HebrewDate.of("נח התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 4),   HebrewDate.of("ד חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 5),   HebrewDate.of("ה חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 6),   HebrewDate.of("ו חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 7),   HebrewDate.of("ז חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 8),   HebrewDate.of("ח חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 9),   HebrewDate.of("ט חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 10),  HebrewDate.of("י חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 10),  HebrewDate.of("לך-לך התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 11),  HebrewDate.of("יא חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 12),  HebrewDate.of("יב חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 13),  HebrewDate.of("יג חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 14),  HebrewDate.of("יד חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 15),  HebrewDate.of("טו חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 16),  HebrewDate.of("טז חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 17),  HebrewDate.of("יז חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 17),  HebrewDate.of("וירא התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 18),  HebrewDate.of("יח חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 19),  HebrewDate.of("יט חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 20),  HebrewDate.of("כ חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 21),  HebrewDate.of("כא חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 22),  HebrewDate.of("כב חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 23),  HebrewDate.of("כג חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 24),  HebrewDate.of("כד חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 24),  HebrewDate.of("חיי-שרה התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 25),  HebrewDate.of("כה חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 26),  HebrewDate.of("כו חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 27),  HebrewDate.of("כז חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 28),  HebrewDate.of("כח חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 29),  HebrewDate.of("כט חשוון התשפב"));
        assertEquals(HebrewDate.of(5782, 2, 29),   HebrewDate.of(5782, "כט חשוון"));
        assertEquals(HebrewDate.of(5782, 2, 29),   HebrewDate.of(5782, 59));
        assertNull(HebrewDate.of("ל חשוון התשפב"));

        assertEquals(HebrewDate.of(5782, 3, 1),   HebrewDate.of("א כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 2),   HebrewDate.of("ב כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 2),   HebrewDate.of("תולדות התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 3),   HebrewDate.of("ג כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 4),   HebrewDate.of("ד כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 5),   HebrewDate.of("ה כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 6),   HebrewDate.of("ו כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 7),   HebrewDate.of("ז כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 8),   HebrewDate.of("ח כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 9),   HebrewDate.of("ט כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 9),   HebrewDate.of("ויצא התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 10),  HebrewDate.of("י כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 11),  HebrewDate.of("יא כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 12),  HebrewDate.of("יב כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 13),  HebrewDate.of("יג כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 14),  HebrewDate.of("יד כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 15),  HebrewDate.of("טו כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 16),  HebrewDate.of("טז כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 16),  HebrewDate.of("וישלח התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 17),  HebrewDate.of("יז כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 18),  HebrewDate.of("יח כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 19),  HebrewDate.of("יט כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 20),  HebrewDate.of("כ כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 21),  HebrewDate.of("כא כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 22),  HebrewDate.of("כב כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 23),  HebrewDate.of("כג כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 23),  HebrewDate.of("וישב התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 24),  HebrewDate.of("כד כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 25),  HebrewDate.of("כה כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 25),  HebrewDate.of("א חנוכה התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 26),  HebrewDate.of("כו כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 26),  HebrewDate.of("נר שני של חנוכה התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 27),  HebrewDate.of("כז כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 28),  HebrewDate.of("כח כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 29),  HebrewDate.of("כט כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 30),  HebrewDate.of("ל כסלו התשפב"));
        assertEquals(HebrewDate.of(5782, 3, 30),  HebrewDate.of(5782, "ל כסלו"));
        assertEquals(HebrewDate.of(5782, 3, 30),  HebrewDate.of(5782, "מקץ"));
        assertEquals(HebrewDate.of(5782, 3, 30),  HebrewDate.of(5782, 89));
        assertNull(HebrewDate.of("לא כסלו התשפב"));

        assertEquals(HebrewDate.of(5782, 4, 1),   HebrewDate.of("א טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 2),   HebrewDate.of("ב טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 3),   HebrewDate.of("ג טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 4),   HebrewDate.of("ד טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 5),   HebrewDate.of("ה טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 6),   HebrewDate.of("ו טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 7),   HebrewDate.of("ז טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 7),   HebrewDate.of("ויגש התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 8),   HebrewDate.of("ח טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 9),   HebrewDate.of("ט טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 10),  HebrewDate.of("י טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 10),  HebrewDate.of("עשרה בטבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 10),  HebrewDate.of("10 בטבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 11),  HebrewDate.of("יא טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 12),  HebrewDate.of("יב טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 13),  HebrewDate.of("יג טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 14),  HebrewDate.of("יד טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 14),  HebrewDate.of("ויחי התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 15),  HebrewDate.of("טו טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 16),  HebrewDate.of("טז טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 17),  HebrewDate.of("יז טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 18),  HebrewDate.of("יח טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 19),  HebrewDate.of("יט טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 20),  HebrewDate.of("כ טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 21),  HebrewDate.of("כא טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 21),  HebrewDate.of("שמות התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 22),  HebrewDate.of("כב טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 23),  HebrewDate.of("כג טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 24),  HebrewDate.of("כד טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 25),  HebrewDate.of("כה טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 26),  HebrewDate.of("כו טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 27),  HebrewDate.of("כז טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 28),  HebrewDate.of("כח טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 29),  HebrewDate.of("כט טבת התשפב"));
        assertEquals(HebrewDate.of(5782, 4, 29),  HebrewDate.of(5782, "כט טבת"));
        assertEquals(HebrewDate.of(5782, 4, 29),  HebrewDate.of(5782, 118));
        assertNull(HebrewDate.of("ל טבת התשפב"));

        assertEquals(HebrewDate.of(5782, 5, 1),   HebrewDate.of("א שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 2),   HebrewDate.of("ב שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 3),   HebrewDate.of("ג שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 4),   HebrewDate.of("ד שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 5),   HebrewDate.of("ה שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 6),   HebrewDate.of("ו שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 7),   HebrewDate.of("ז שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 8),   HebrewDate.of("ח שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 9),   HebrewDate.of("ט שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 10),  HebrewDate.of("י שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 11),  HebrewDate.of("יא שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 12),  HebrewDate.of("יב שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 13),  HebrewDate.of("יג שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 14),  HebrewDate.of("יד שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 15),  HebrewDate.of("טו שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 15),  HebrewDate.of("15 בשבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 16),  HebrewDate.of("טז שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 17),  HebrewDate.of("יז שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 18),  HebrewDate.of("יח שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 19),  HebrewDate.of("יט שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 20),  HebrewDate.of("כ שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 21),  HebrewDate.of("כא שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 22),  HebrewDate.of("כב שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 23),  HebrewDate.of("כג שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 24),  HebrewDate.of("כד שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 25),  HebrewDate.of("כה שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 26),  HebrewDate.of("כו שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 27),  HebrewDate.of("כז שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 28),  HebrewDate.of("כח שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 29),  HebrewDate.of("כט שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 30),  HebrewDate.of("ל שבט התשפב"));
        assertEquals(HebrewDate.of(5782, 5, 30),   HebrewDate.of(5782, "ל שבט"));
        assertEquals(HebrewDate.of(5782, 5, 30),   HebrewDate.of(5782, 148));
        assertNull(HebrewDate.of("לא שבט התשפב"));

        assertEquals(HebrewDate.of(5782, 6, 1),   HebrewDate.of("א אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 1),   HebrewDate.of(5782, "א אדר-א"));
        assertEquals(HebrewDate.of(5782, 6, 2),   HebrewDate.of("ב אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 3),   HebrewDate.of("ג אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 4),   HebrewDate.of("ד אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 5),   HebrewDate.of("ה אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 6),   HebrewDate.of("ו אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 7),   HebrewDate.of("ז אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 8),   HebrewDate.of("ח אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 9),   HebrewDate.of("ט אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 10),  HebrewDate.of("י אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 11),  HebrewDate.of("יא אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 12),  HebrewDate.of("יב אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 13),  HebrewDate.of("יג אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 14),  HebrewDate.of("יד אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 14),  HebrewDate.of("פורים קטן התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 15),  HebrewDate.of("טו אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 16),  HebrewDate.of("טז אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 17),  HebrewDate.of("יז אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 18),  HebrewDate.of("יח אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 19),  HebrewDate.of("יט אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 20),  HebrewDate.of("כ אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 21),  HebrewDate.of("כא אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 22),  HebrewDate.of("כב אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 23),  HebrewDate.of("כג אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 24),  HebrewDate.of("כד אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 25),  HebrewDate.of("כה אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 26),  HebrewDate.of("כו אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 27),  HebrewDate.of("כז אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 28),  HebrewDate.of("כח אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 29),  HebrewDate.of("כט אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 30),  HebrewDate.of("ל אדר-א התשפב"));
        assertEquals(HebrewDate.of(5782, 6, 30),   HebrewDate.of(5782, "ל אדר-א"));
        assertEquals(HebrewDate.of(5782, 6, 30),   HebrewDate.of(5782, 178));
        assertNull(HebrewDate.of("לא אדר-א התשפב"));

        assertEquals(HebrewDate.of(5782, 7, 1),   HebrewDate.of("א אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 1),   HebrewDate.of("א אדר-ב התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 1),   HebrewDate.of(5782, "א אדר"));
        assertEquals(HebrewDate.of(5782, 7, 2),   HebrewDate.of("ב אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 3),   HebrewDate.of("ג אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 4),   HebrewDate.of("ד אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 5),   HebrewDate.of("ה אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 6),   HebrewDate.of("ו אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 7),   HebrewDate.of("ז אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 8),   HebrewDate.of("ח אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 9),   HebrewDate.of("ט אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 10),  HebrewDate.of("י אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 11),  HebrewDate.of("יא אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 12),  HebrewDate.of("יב אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 13),  HebrewDate.of("יג אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 14),  HebrewDate.of("יד אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 14),  HebrewDate.of("פורים התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 15),  HebrewDate.of("טו אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 16),  HebrewDate.of("טז אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 17),  HebrewDate.of("יז אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 18),  HebrewDate.of("יח אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 19),  HebrewDate.of("יט אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 20),  HebrewDate.of("כ אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 21),  HebrewDate.of("כא אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 22),  HebrewDate.of("כב אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 23),  HebrewDate.of("כג אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 24),  HebrewDate.of("כד אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 25),  HebrewDate.of("כה אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 26),  HebrewDate.of("כו אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 27),  HebrewDate.of("כז אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 28),  HebrewDate.of("כח אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 29),  HebrewDate.of("כט אדר התשפב"));
        assertEquals(HebrewDate.of(5782, 7, 29),   HebrewDate.of(5782, "כט אדר"));
        assertEquals(HebrewDate.of(5782, 7, 29),   HebrewDate.of(5782, 207));
        assertNull(HebrewDate.of("לא אדר התשפב"));

        assertEquals(HebrewDate.of(5782, 8, 1),   HebrewDate.of("א ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 1),   HebrewDate.of(5782, "א ניסן"));
        assertEquals(HebrewDate.of(5782, 8, 2),   HebrewDate.of("ב ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 3),   HebrewDate.of("ג ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 4),   HebrewDate.of("ד ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 5),   HebrewDate.of("ה ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 6),   HebrewDate.of("ו ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 7),   HebrewDate.of("ז ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 8),   HebrewDate.of("ח ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 9),   HebrewDate.of("ט ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 10),  HebrewDate.of("י ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 11),  HebrewDate.of("יא ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 12),  HebrewDate.of("יב ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 13),  HebrewDate.of("יג ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 14),  HebrewDate.of("יד ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 15),  HebrewDate.of("טו ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 16),  HebrewDate.of("טז ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 17),  HebrewDate.of("יז ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 18),  HebrewDate.of("יח ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 19),  HebrewDate.of("יט ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 20),  HebrewDate.of("כ ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 21),  HebrewDate.of("כא ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 22),  HebrewDate.of("כב ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 23),  HebrewDate.of("כג ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 24),  HebrewDate.of("כד ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 25),  HebrewDate.of("כה ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 26),  HebrewDate.of("כו ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 27),  HebrewDate.of("כז ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 28),  HebrewDate.of("כח ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 29),  HebrewDate.of("כט ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 30),  HebrewDate.of("ל ניסן התשפב"));
        assertEquals(HebrewDate.of(5782, 8, 30),   HebrewDate.of(5782, "ל ניסן"));
        assertEquals(HebrewDate.of(5782, 8, 30),   HebrewDate.of(5782, 237));
        assertNull(HebrewDate.of("לא ניסן התשפב"));

        assertEquals(HebrewDate.of(5782, 9, 1),   HebrewDate.of("א אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 1),   HebrewDate.of(5782, "א אייר"));
        assertEquals(HebrewDate.of(5782, 9, 2),   HebrewDate.of("ב אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 3),   HebrewDate.of("ג אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 4),   HebrewDate.of("ד אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 5),   HebrewDate.of("ה אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 6),   HebrewDate.of("ו אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 7),   HebrewDate.of("ז אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 8),   HebrewDate.of("ח אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 9),   HebrewDate.of("ט אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 10),  HebrewDate.of("י אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 11),  HebrewDate.of("יא אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 12),  HebrewDate.of("יב אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 13),  HebrewDate.of("יג אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 14),  HebrewDate.of("יד אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 15),  HebrewDate.of("טו אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 16),  HebrewDate.of("טז אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 17),  HebrewDate.of("יז אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 18),  HebrewDate.of("יח אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 19),  HebrewDate.of("יט אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 20),  HebrewDate.of("כ אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 21),  HebrewDate.of("כא אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 22),  HebrewDate.of("כב אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 23),  HebrewDate.of("כג אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 24),  HebrewDate.of("כד אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 25),  HebrewDate.of("כה אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 26),  HebrewDate.of("כו אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 27),  HebrewDate.of("כז אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 28),  HebrewDate.of("כח אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 29),  HebrewDate.of("כט אייר התשפב"));
        assertEquals(HebrewDate.of(5782, 9, 29),   HebrewDate.of(5782, "כט אייר"));
        assertEquals(HebrewDate.of(5782, 9, 29),   HebrewDate.of(5782, 266));
        assertNull(HebrewDate.of("ל אייר התשפב"));

        assertEquals(HebrewDate.of(5782, 10, 1),   HebrewDate.of("א סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 1),   HebrewDate.of(5782, "א סיוון"));
        assertEquals(HebrewDate.of(5782, 10, 2),   HebrewDate.of("ב סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 3),   HebrewDate.of("ג סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 4),   HebrewDate.of("ד סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 5),   HebrewDate.of("ה סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 6),   HebrewDate.of("ו סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 7),   HebrewDate.of("ז סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 8),   HebrewDate.of("ח סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 9),   HebrewDate.of("ט סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 10),  HebrewDate.of("י סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 11),  HebrewDate.of("יא סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 12),  HebrewDate.of("יב סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 13),  HebrewDate.of("יג סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 14),  HebrewDate.of("יד סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 15),  HebrewDate.of("טו סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 16),  HebrewDate.of("טז סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 17),  HebrewDate.of("יז סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 18),  HebrewDate.of("יח סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 19),  HebrewDate.of("יט סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 20),  HebrewDate.of("כ סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 21),  HebrewDate.of("כא סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 22),  HebrewDate.of("כב סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 23),  HebrewDate.of("כג סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 24),  HebrewDate.of("כד סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 25),  HebrewDate.of("כה סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 26),  HebrewDate.of("כו סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 27),  HebrewDate.of("כז סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 28),  HebrewDate.of("כח סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 29),  HebrewDate.of("כט סיוון התשפב"));
        assertEquals(HebrewDate.of(5782, 10, 29),   HebrewDate.of(5782, "כט סיוון"));
        assertEquals(HebrewDate.of(5782, 10, 29),   HebrewDate.of(5782, 295));
        assertNull(HebrewDate.of("לא סיוון התשפב"));

        assertEquals(HebrewDate.of(5782, 11, 1),   HebrewDate.of("א תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 1),   HebrewDate.of(5782, "א תמוז"));
        assertEquals(HebrewDate.of(5782, 11, 2),   HebrewDate.of("ב תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 3),   HebrewDate.of("ג תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 4),   HebrewDate.of("ד תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 5),   HebrewDate.of("ה תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 6),   HebrewDate.of("ו תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 7),   HebrewDate.of("ז תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 8),   HebrewDate.of("ח תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 9),   HebrewDate.of("ט תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 10),  HebrewDate.of("י תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 11),  HebrewDate.of("יא תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 12),  HebrewDate.of("יב תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 13),  HebrewDate.of("יג תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 14),  HebrewDate.of("יד תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 15),  HebrewDate.of("טו תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 16),  HebrewDate.of("טז תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 17),  HebrewDate.of("יז תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 18),  HebrewDate.of("יח תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 19),  HebrewDate.of("יט תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 20),  HebrewDate.of("כ תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 21),  HebrewDate.of("כא תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 22),  HebrewDate.of("כב תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 23),  HebrewDate.of("כג תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 24),  HebrewDate.of("כד תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 25),  HebrewDate.of("כה תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 26),  HebrewDate.of("כו תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 27),  HebrewDate.of("כז תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 28),  HebrewDate.of("כח תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 29),  HebrewDate.of("כט תמוז התשפב"));
        assertEquals(HebrewDate.of(5782, 11, 29),  HebrewDate.of(5782, "כט תמוז"));
        assertEquals(HebrewDate.of(5782, 11, 29),   HebrewDate.of(5782, 325));
        assertNull(HebrewDate.of("ל תמוז התשפב"));

        assertEquals(HebrewDate.of(5782, 12, 1),   HebrewDate.of("א אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 1),   HebrewDate.of(5782, "א אב"));
        assertEquals(HebrewDate.of(5782, 12, 2),   HebrewDate.of("ב אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 3),   HebrewDate.of("ג אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 4),   HebrewDate.of("ד אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 5),   HebrewDate.of("ה אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 6),   HebrewDate.of("ו אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 7),   HebrewDate.of("ז אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 8),   HebrewDate.of("ח אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 9),   HebrewDate.of("ט אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 10),  HebrewDate.of("י אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 11),  HebrewDate.of("יא אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 12),  HebrewDate.of("יב אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 13),  HebrewDate.of("יג אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 14),  HebrewDate.of("יד אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 15),  HebrewDate.of("טו אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 16),  HebrewDate.of("טז אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 17),  HebrewDate.of("יז אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 18),  HebrewDate.of("יח אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 19),  HebrewDate.of("יט אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 20),  HebrewDate.of("כ אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 21),  HebrewDate.of("כא אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 22),  HebrewDate.of("כב אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 23),  HebrewDate.of("כג אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 24),  HebrewDate.of("כד אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 25),  HebrewDate.of("כה אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 26),  HebrewDate.of("כו אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 27),  HebrewDate.of("כז אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 28),  HebrewDate.of("כח אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 29),  HebrewDate.of("כט אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 29),  HebrewDate.of("כט אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 30),  HebrewDate.of("ל אב התשפב"));
        assertEquals(HebrewDate.of(5782, 12, 30),   HebrewDate.of(5782, "ל אב"));
        assertEquals(HebrewDate.of(5782, 12, 30),   HebrewDate.of(5782, 355));
        assertNull(HebrewDate.of("לא אב התשפב"));

        assertEquals(HebrewDate.of(5782, 13, 1),   HebrewDate.of("א אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 1),   HebrewDate.of(5782, "א אלול"));
        assertEquals(HebrewDate.of(5782, 13, 2),   HebrewDate.of("ב אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 3),   HebrewDate.of("ג אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 4),   HebrewDate.of("ד אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 5),   HebrewDate.of("ה אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 6),   HebrewDate.of("ו אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 7),   HebrewDate.of("ז אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 8),   HebrewDate.of("ח אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 9),   HebrewDate.of("ט אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 10),  HebrewDate.of("י אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 11),  HebrewDate.of("יא אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 12),  HebrewDate.of("יב אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 13),  HebrewDate.of("יג אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 14),  HebrewDate.of("יד אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 15),  HebrewDate.of("טו אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 16),  HebrewDate.of("טז אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 17),  HebrewDate.of("יז אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 18),  HebrewDate.of("יח אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 19),  HebrewDate.of("יט אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 20),  HebrewDate.of("כ אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 21),  HebrewDate.of("כא אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 22),  HebrewDate.of("כב אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 23),  HebrewDate.of("כג אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 24),  HebrewDate.of("כד אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 25),  HebrewDate.of("כה אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 26),  HebrewDate.of("כו אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 27),  HebrewDate.of("כז אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 28),  HebrewDate.of("כח אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 29),  HebrewDate.of("כט אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 29),  HebrewDate.of("כט אלול התשפב"));
        assertEquals(HebrewDate.of(5782, 13, 29),   HebrewDate.of(5782, "כט אלול"));
        assertEquals(HebrewDate.of(5782, 13, 29),   HebrewDate.of(5782, 384));
        assertNull(HebrewDate.of("ל אלול התשפב"));

        // אדר א בתשפג זו טעות ובכל זאת הוא מבין
        assertEquals(HebrewDate.of(5783, 6, 1),   HebrewDate.of("א אדר-א התשפג"));
        assertEquals(HebrewDate.of(5783, 6, 1),   HebrewDate.of("א אדר-ב התשפג"));
        assertEquals(HebrewDate.of(5783, 6, 1),   HebrewDate.of("א אדר התשפג"));
        assertEquals(HebrewDate.of(5783, 6, 1),   HebrewDate.of(5783, "א אדר-א"));
        assertEquals(HebrewDate.of(5783, 6, 1),   HebrewDate.of(5783, "א אדר-ב"));
        assertEquals(HebrewDate.of(5783, 6, 1),   HebrewDate.of(5783, "א אדר"));
    }

    @Test
    public void ofChris()
    {
        assertNull(HebrewDate.ofChris(2021, 1, 0));
        assertNull(HebrewDate.ofChris(2021, 0, 1));

        assertEquals(HebrewDate.ofChris(2021, 1, 1), HebrewDate.of(LocalDate.of(2021, 1, 1)));
        assertEquals(HebrewDate.ofChris(2021, 1, 30), HebrewDate.of(LocalDate.of(2021, 1, 30)));
        assertEquals(HebrewDate.ofChris(2021, 30), HebrewDate.of(LocalDate.of(2021, 1, 30)));
        assertEquals(HebrewDate.ofChris(2021, 31), HebrewDate.of(LocalDate.of(2021, 1, 31)));
        assertNull(HebrewDate.ofChris(2021, 1, 32));

        assertEquals(HebrewDate.ofChris(2021, 2, 1), HebrewDate.of(LocalDate.of(2021, 2, 1)));
        assertEquals(HebrewDate.ofChris(2021, 32), HebrewDate.of(LocalDate.of(2021, 2, 1)));
        assertEquals(HebrewDate.ofChris(2021, 2, 28), HebrewDate.of(LocalDate.of(2021, 2, 28)));
        assertEquals(HebrewDate.ofChris(2021, 59), HebrewDate.of(LocalDate.of(2021, 2, 28)));
        assertNull(HebrewDate.ofChris(2021, 2, 29));

        assertEquals(HebrewDate.ofChris(2021, 3, 1), HebrewDate.of(LocalDate.of(2021, 3, 1)));
        assertEquals(HebrewDate.ofChris(2021, 60), HebrewDate.of(LocalDate.of(2021, 3, 1)));
        assertEquals(HebrewDate.ofChris(2021, 3, 31), HebrewDate.of(LocalDate.of(2021, 3, 31)));
        assertEquals(HebrewDate.ofChris(2021, 90), HebrewDate.of(LocalDate.of(2021, 3, 31)));
        assertNull(HebrewDate.ofChris(2021, 3, 32));
    }

    @Test
    public void now()
    {
        assertEquals(LocalDate.now(), HebrewDate.now().getLocalDate());

    }

    @Test
    public void checkYears()
    {
        HebrewDate date = HebrewDate.of(1, 1);
        for (int year = 1; year < 6000; year += 9)
        {
            assertEquals(year, HebrewDate.of("א תשרי " + date.getYearString()).getYear());
            date.addYears(9);
        }
    }
}
